---
- name: install mongo db
  become: yes
  hosts: all
  tasks: 
    - name: add apt_key
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present
    - name: create a list file for your MongoDB package
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
        state: present
        filename: /etc/apt/sources.list.d/mongodb-org-5.0.list
    - name: install mongod
      apt:
        name: mongodb-org
        update_cache: yes
        state: present
    - name: systemd
      ansible.builtin.systemd:
        name: mongod
        enabled: yes
        state: started
        
          